# Generated by Django 3.1.4 on 2020-12-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='option_tree',
            new_name='option_three',
        ),
    ]
